### ISSUE TITLE
Addon currently not working on KODI / SMPC running on Android, but DOES WORK running on Linux / Windows

### ISSUE THREAD

**Issue by friedretinas** [dandy0850/dandymedia#1]
First I want to thank you for all the work you (& Mucky Duck) havw done that has led to your creation of this excellent addon,  So, I'm sorry to be the one to report that it currently no longer seems to be working on KODI / SMPC running on Android.  However, it DOES STILL WORK when using it w/ KODI running on Linux / Windows.  

A little over a week ago it was working perfectly regardless of the underlying OS & hardware platform, but if the underlying OS is Android or Android-based (Fire TV OS), it generates an when trying to select a sub-category option (i.e. "Trending Movies") regardless of hardware, KODI-based media center derivation, etc.  **I am aware that work for the 1.1.0 version of the addon is noted as being completed "4 days ago" and that is the version that I've been using in all of my testing.**

I've  posted a (typical) KODI log for inspection at https://ares-project.uk/logupload/log.php?id=608438 that is representative of the errors I've been experiencing. & the same type of error is observed each time regardless of the following Android-based configurations that I used when conducting my testing to ensure that the problem is not specific to hardware, or only KODI, only Fire TV OS. etc.:

HARDWARE: Beelink Mini M8S running the most recent Beelink Firmware Update / Android 5.1.1. + Software:

1.  KODI 16,1 (official / stable release) 
2. SPMC 16.5.5 (latest release) 

HARDWARE: 1nd Gen Fire TV Stick running the most recent Fire OS System of the previous User Interface (since no other update have yet to be issued for the 1st gen sticks) + Software:

1.  KODI 16,1 (official / stable release) 
2. SPMC 16.5.5 (latest release) 

HARDWARE: 2nd Gen Fire TV Stick running the most recent Fire OS System Update + Software:

1.  KODI 16,1 (official / stable release) 
2. SPMC 16.5.5 (latest release) 

I'm also willing to install Krypton on any the above hardware platforms & test the addon w/ it too, but didn't do that because it remains in Beta status release. If you need any other information, I'm happy to provide what I can. Thank you.

**Comment by dandy0850** [comment]
Thank you. I am aware of the droid issue. Hopefully a solution will be found.



Regards
Grant Wiltshire


-------- Original message --------
