### ISSUE TITLE
toonkeeda-gw is not working

### ISSUE THREAD

**Issue by bjgood** [dandy0850/dandymedia#10]
Hey Dandy,
toonkeeda_gw is not working. It showed an error message when I tried it yesterday.

Thought I'd pass it along.

Have a good one, Dandy. :).

Later...

**Comment by dandy0850** [comment]
TY - addon seems fine , hit a few error links site showing as server issues, hopefully sort self

**Comment by bjgood** [comment]
Hey Dandy,
You're right, it does work...just not for the series I want (for my son). It's Spongebob. At ToonKeeda they list the name of each episode/segment . With WatchCartoonOnline_gw each link only plays the first segment of an episode for Spongebob...the second (or third...if applicable) does not. On WatchCartoonOnline website it does play.

Thanks anyways, Dandy.

Later...

**Comment by dandy0850** [comment]
I will have a look see whats going on

**Comment by dandy0850** [comment]
ToonKeeda has many missing episodes - watchcartoon what do you mean it starts playing and stops ? Or episodes missing ? I cant find issue just tried 4 random and ok and played thru , give me episode example pls

**Comment by bjgood** [comment]
On WatchCartoonOnline_gw the only series that I've seen so far that doesn't play the full episode (including segments of an episode) is Spongebob Squarepants. For example, season 1 episode 1 shows segments Help Wanted , Reef Blower, and Tea at the Treedome. These 3 segments make up season 1 episode 1. Yet, only Help Wanted will play. The other two segments are not played at all.

Hope I made it clear.

I don't think its worth looking into this too deep. It's only one series that has this problem.

Later...

**Comment by dandy0850** [comment]
Hmm yes can see the issue now on the site 3 videos embeded ? , Not gonna be easy one resolve !

**Comment by bjgood** [comment]
Yeah, but if anyone can solve it...it's you. ;).

We all love a challenge. Today I've been working on a bash script I use to update libflashplayer in Ubuntu. The adobe beta site has lately been changing things...which screwed up how my bash script worked. I decided to try a new approach to solve it. It should work now no matter what they do...hopefully. I also enjoy the challenge in solving it. I know you do as well. Most coders do.

Later...

**Comment by dandy0850** [comment]
was thinkin add pop up dialog if more than one vid , if vid 2 present in page else as is, sort of thing - just wanna try make sure dont effect others

**Comment by bjgood** [comment]
Most series have one video for each episode even if there are two titles listed...like Garfield and Friends, T.U.F.F Puppy, Back at the Barnyard, or The Mighty B!. Is there a way to tie the segments videos of an episode together to play one after the other?

Have a good day, Dandy.

Later...

**Comment by dandy0850** [comment]
Tried few ways - Spongebob diff - 3 seperate videos , with not on lot on the page to tag onto to recognise , especially without messing up the play from here option with a dialog box ...............I will keep thinkin

**Comment by dandy0850** [comment]
Right version in repo (not pushed as update) v1.1.41, try see what think/way ive gone .
Think will effect others with multiple links to same rather than multiple videos (different).
Issues being very little absolute to tag on for [if] statement , need check how effect others needlessly.
Cant split names much more in popup dialog because not uniformed used the url, without adding more if/else++ 
Is it only Spongebob ? with multiple videos (must be others) else could just [if]  spongebob resolve this way 

Any way Im gonna lie in a dark room - brain fried , didnt have a lot to start with

Let me know

**Comment by bjgood** [comment]
Hey Dandy,
The new version works well with Spongebob. Thanks. As far as other series that are like Spongebob in structure...I have no idea. I'm sure there are...as you said, but I've never run across any others. In def resolve I changed 'label = label.split('file=')[1].split('.flv')[0]' to 'label = label.split('- ')[2].split('.flv')[0], which got rid of the long string of characters preceding the episode name (example: it shows 'Help Wanted' or 'Reef Blower' or 'Tea at the Treedome' individually in the dialog box for S1E1) at least for Spongebob.

Let that great brain of yours cool down, Dandy. I'm amazed at how well you've solved this problem. No problem, either, with other series playing with this new code added.

Thanks very much for your great effort. This goes to show what a great coder you are.

Have a good day, Dandy. :).

Best regards,
Bob

**Comment by dandy0850** [comment]
Yes i did exactly the same for split but will error further down, its not uniformed throughout the list, think was about S3 started changing , i will have another look , probably just do [if] for spongebob for now cause will mess up others and see if others come to light.

Many thanks

**Comment by dandy0850** [comment]
The plot thickens, found 3 urls, i got to this !!

label = label.split('file=')[1].split('.flv')[0]
 if 'Spongebob.squarepants.' in label:
          label = label.split('Spongebob.squarepants.')[1].replace('.',' ').title()                
else:
       try:
           label = label.split('- ')[2]
      except:
           label= label.split('- ')[1]

**Comment by bjgood** [comment]
You were right. Further down the list at season 3 I started receiving errors with my code change. But with your above code added it plays fine. Thanks, Dandy.

Yesterday, at WatchCartoonOnline's web site, I started down their cartoon list looking for any other series similar to Spongebob in structure. I made it through the D's, without a match, before I stopped for the day.

This is an awful lot of trouble for just one series, Dandy. What say you add the above code to WCO_gw and be done with it. Your solution was very inventive and should work with any series.

Thanks, Dandy. Have a good day.

Regards,
Bob

**Comment by dandy0850** [comment]
I will push update with just Spongebob sorted so son sorted (seeing he found the issue). I have found a couple of others , need have good look see if another tag to latch on to in the html  

I gotta stop lookin at it for a bit im going mad LOL

**Comment by bjgood** [comment]
Cool that big brain, Dandy! ;). Take a break, if possible. :). Coding is an obsessive hobby.

Big thanks.
Bob

**Comment by bjgood** [comment]
New version works great for Spongebob. Thanks for your excellent work on this. Sorry for all the trouble I caused you. It was just one series. You're obviously a very nice fellow to put up with me.

Thanks, again, Dandy. :).

BTW, did you ever think over whether it was possible to play those episodes that have separate videos one after the other? 

Have a good day, bud.

Best regards,
Bob

**Comment by dandy0850** [comment]
Not problem need user help.
They separate files so unless there's a way im unaware of , in truth I don't know.
Was a way to rename files from drives and get to play as one 

I have found few others - more head scratching

**Comment by bjgood** [comment]
Hi Dandy,
Why did you decide to obfuscate the code in version 1.1.6 of watchcartoon_gw? I can't make heads or tails of the code now. I'm sure that's the whole point of doing it.

Have a good one.

Bob

**Comment by dandy0850** [comment]
Been copied elsewhere stopping others from learning is not my intention at all and happy to help anyone and have done, in the spirit of open source , these sorts come and go - i will un-obfuscate with future updates. 
Post me a contact email i will send un-obfuscated version or PM on twitter @DandyMedia

**Comment by bjgood** [comment]
Dandy,
v1.1.6 is the same as v1.1.5 except now it's encrypted. Right?

I don't think it would be wise for me to post my email address here, and I don't have a twitter account. And, from what I can tell, you can't PM at your github, either. I may be wrong about that, but I can't find it.

Later Dandy.

Bob

Who stole your addon? Or did they steal a section of code of yours from watchcartoon_gw?

**Comment by dandy0850** [comment]
Yeah just obfuscated
thats why i mentioned twitter, cant PM here anymore
so if still got py 115 ok for now 
- only temp 
I unobfuscate in future

**Comment by bjgood** [comment]
Hi Dandy, :)
Just dropped by to say "Hi", first of all, and to thank you again for your excellent coding solution in WatchCartoonOnline for the SpongeBob series thing. It works great! I can never thank you enough for all the hard work you put into it. Like I said before, you're obviously a very friendly and nice fellow.

Thanks for putting up with me. :).

Later, Dandy.

Bob

**Comment by dandy0850** [comment]
No probs is a few others - but my son uses addon everyday - least workin , thx for all help

**Comment by bjgood** [comment]
Hi Dandy,
I read on another site that you had removed a few of your addons...and sure enough you have. Particularly WCO. Are you in a country where the MPA can get to you?

I'll try to PM you at kodi.tv. I'd like to keep in contact with you.

You bud,
Bob

**Comment by dandy0850** [comment]
aint worked months
