### ISSUE TITLE
Watchcartoononline

### ISSUE THREAD

**Issue by bjgood** [dandy0850/dandymedia#5]
Hi,
I just discovered your repo. Nice. You've got a lot of really nice addons. Congrats on you efforts. :).

It would be great if you could sort the episodes, within watchcartoononline, starting from season 1 down to the last season. That would make going through them a bit easier. Also, it would be great if you could strip the title (like T.U.F.F Puppy) from the link that is displayed in the results screen just leaving Season 1 Episode 17 plus the episode name.

Thanks for your great addons.
Best regards,
Bob

**Comment by dandy0850** [comment]
Did not strip episode titles as not all are uniformed same format, will have look see if any other way to remove title not sure - episodes listed descending  as are on site - cant please everyone realise this means 'play from here' in reverse. But many would then want latest episodes at top anyway too to not have scroll all way down if lots seasons and new episodes are added.

**Comment by bjgood** [comment]
Hi Dandy,
Were you aware there "was" an addon called WatchCartoonOnline by a dude named spoyser (the same guy who made Super Favorites)? Yes, it was for the same website. He pissed a group of people off and they decided to DoS his websites. He threw in the towel and stopped development on all his addons. This happened a few months back. Some of them have stopped working which includes WatchCartoonOnline. In his he sorted the episides from Season 1 to last season, plus a lot of other stuff. If you want I can see if I can find his last version of WCO and send it to you.

**Comment by dandy0850** [comment]
As far as i was aware and dont know the guy directly he had given up I was asked if I would do the site , as I said I will look back at it when I get a chance
