### ISSUE TITLE
EITHER REMOVE "addDir('[B][COLOR cornflowerblue]Search[/COLOR][/B]','url',6,ART + 'search.jpg',FANART,'')  OR ADD BACK & FIX  def Search():   & RELATED SOURCE CODE

### ISSUE THREAD

**Issue by friedretinas** [dandy0850/dandymedia#6]
(The following in reference to the OPENLOAD addon; my bad for not specifying as such in the subject line.)

EITHER REMOVE 
      `"addDir('[B][COLOR cornflowerblue]Search[/COLOR][/B]','url',6,ART + 'search.jpg',FANART,'')` 

OR ADD BACK & MODIFY  `def Search(): ` & RELATED SOURCE CODE. 

I took some of the relevant code (that I found in 1.1.2 rel. source code) and added it back to 1.1.8 release. And then, with just a few very basic modifications (**see below**). I ended up with a working Movie (only) Search. Although my fix doesn't provide the much more robust "Search" functionality that could be implemented, at least it does provide a "Search" that doesn't generate KODI logfile errors. 

```
def Search():
        keyb = xbmc.Keyboard('', 'Search')
        keyb.doModal()
        if (keyb.isConfirmed()):
                search = keyb.getText().replace(' ','+')
                url = BASEURL + '/?s=' + search
                search_res(url)

def search_res(url):
    OPEN = open_url(url).content
    Regex = re.compile('<div class="result-item">.+?<a href="(.+?)">.+?<img src="(.+?)" alt="(.+?)"',re.DOTALL).findall(OPEN)
    for url,icon,name in Regex:
            name = name.replace('&#8217;','').replace('#038;','')
            icon = icon.replace('w90','w300_and_h450_bestv2')
            addDir('[B][COLOR white]%s[/COLOR][/B]' %name,url,10,icon,FANART,'')
    xbmc.executebuiltin('Container.SetViewMode(50)')
```

Why were the "Search" related source code functions removed in the first place? 

 I could understand removing that code if `"addDir('[B][COLOR cornflowerblue]Search[/COLOR][/B]','url',6,ART + 'search.jpg',FANART,'')`  had also been removed, but that line hasn't been removed as of the current 1.1.8 release. 

Who thought it would be a good idea to leave in a non-working "Search" menu option for which all the underlying code needed to support it had been removed, which in turn always generates an error informing the average (non-programmer) KODI user to check the KODI log?

**Comment by dandy0850** [comment]
Thank you for your condescending request - This was obviously omitted in error , a simple 'Did you know' -  would have sufficed .
Anyone can write,release and maintain a plugin for Kodi , why not try yourself

**Comment by bjgood** [comment]
I agree with you Dandy. It was a rather rude request. Almost a demand.

Later...
