### ISSUE TITLE
plugin.video.t4charts

### ISSUE THREAD

**Issue by vTneilA** [dandy0850/dandymedia#7]
Hi, there.. 

plugin.video.t4charts is not working on kodi 17.. any chance to update?

**Comment by vTneilA** [comment]
[https://www.dropbox.com/s/5cce3aw064p023b/plugin.video.t4charts.zip?dl=1](url)

**Comment by vTneilA** [comment]
https://www.dropbox.com/s/5cce3aw064p023b/plugin.video.t4charts.zip?dl=1

**Comment by dandy0850** [comment]
Thank you for letting know was unaware of issue, and thanks for your input.
I have pushed update as is - I will have a look at again think can update again and improve abit
