### ISSUE TITLE
Episodes in WatchCartoonOnline sort order

### ISSUE THREAD

**Issue by ZeroGwafa** [dandy0850/dandymedia#8]
Looks like the episodes are in descending order (Which, I know is how they are ordered on the site).  However, you cannot sort these into ascending order using KODI's GUI.  

This also prevents queuing up an entire series starting at episode 1.

Otherwise, great work!

**Comment by dandy0850** [comment]
Also cant please everybody as some would want the latest added episode at the top as new ones are added especially if large list with many episodes as some are.

**Comment by bjgood** [comment]
Hi Dandy,
If you add "Regex2 = list(reversed(Regex2))" to a category in WatchCartoonOnline the cartoon list is sorted in an ascending order.

Example:
def Get_show_episodes(url):
    OPEN = Open_Url(url)
    Regex = re.compile('class="cat-listview cat-listbsize">(.+?)</ul>',re.DOTALL).findall(OPEN)
    Regex2 = re.compile('<a href="(.+?)".+?title="(.+?)"',re.DOTALL).findall(str(Regex))
    Regex2 = list(reversed(Regex2))
    for url,name in Regex2:

I use the cartoon list to find cartoons that my kids and I want to watch. That's why I used that example. Try it...it works.

Getting rid of the title of the cartoon series was a bit harder to do. What I did was add each title to the name = name.replace section. Not very efficient...but it works.

Later...
Bob

**Comment by dandy0850** [comment]
As said before cant please everyone can change it as you have said. Im sure with the name.replace there was an issue with some of them I came across where this will cause , cant remember now - I will have a look when get chance.
Thanks for your input

**Comment by dandy0850** [comment]
Had quick look , reversed series list , carried name forward and replaced seems work for most though wont for all due to the suffix - can go through and change add different tag. But seems work better as I assume looked awful on many skins.....enjoy for now 

All the best Dandy

**Comment by bjgood** [comment]
Hi Dandy,
I added this under Get_show_episodes...

        if 'Season' in name:
           name = name.replace('Season ','').replace(' Episode ','x')
        name = name.replace(bollox,'')
        addDir('%s' %name,url,100,icon,icon,name)
        xbmc.executebuiltin('Container.SetViewMode(50)')

It looks, for example, like...1x1, 1x2, 1x3, etc.. Shortens the episode listing quite a bit. For episodes only (no season), I left it alone. BTW, thanks for the "Title" removal (bollox). :).

I will say this, Dandy, that your version of WatchCartoonOnline plays better than spoyser's. With his, some episodes of a series just wouldn't play...even whole series (anything involving animeuploads). But with yours, they all play. Your def resolve section is the key. I've even tried to integrate that code into Sean's version, but I just couldn't get it to work. So congratulations on your coding abilities. 

Later...
Bob

**Comment by dandy0850** [comment]
Yep good idea will have look see if ok across all but again an improvement.  I wrote completely from scratch  see few different ways of playback to catch all , hopefully stays sound so far has. I'm learning as I go along and have enjoyed doing everything I've done so far. Thanks for compliment

**Comment by bjgood** [comment]
Hi Dandy,
I added this under Get_show_episodes...
before:
        name = name.replace('English Dubbed','[COLOR blue](English Dubbed)[/COLOR]').replace('English Subbed','[COLOR red](English Subbed)[/COLOR]').replace('Watch ','')

after:
        name = name.replace('English Dubbed','[COLOR blue](English Dubbed)[/COLOR]').replace('English Subbed','[COLOR red](English Subbed)[/COLOR]').replace('Watch ','',1)

The 1 in .replace('Watch ','',1) limits the replacement of Watch to just one occurrence. I actually had an episode that contained Watch in the episode name. This fixed it.

Just trying to help.

Later...
Bob

**Comment by dandy0850** [comment]
LOL - unfortunate - will look at when i get chance , still not checked last addition - I will 

I got no problem what so ever with any input much appreciated

**Comment by bjgood** [comment]
Hey Dandy,
In the def Get_show_episodes>name = name.replace section, you have replace('amp',''). This should be replace('&amp','&')...like you already have in other def name  = name.replace sections. Small point, but I thought I'd mention it.

BTW, i found an episode of a series (Shaun the Sheep> episode 149) that your addon wouldn't play. The first one I've run across. It involves resolving animeuploads (at least according to the website).

Later...

**Comment by dandy0850** [comment]
Thanks will get chance to look hectic week will sort all previous

**Comment by dandy0850** [comment]
Shaun the Sheep ep149 - Media unavailable on the site

**Comment by dandy0850** [comment]
Pushed an update [1.1.2]
Added your suggestions seems ok for many/most , never gonna get this perfect for  ALL the site not in complete unison, even the order reversal fine for the 'Play from here' continuous playback option but many would want latest at top, and some are even in ascending order so the reversal the puts them backwards. 
Cant please everyone , But we can make good as much as can be.

I thank you once again for your input 'bjgood', great improvements, any help appreciated as all benefit
