### ISSUE TITLE
I have an idea

### ISSUE THREAD

**Issue by bjgood** [dandy0850/dandymedia#9]
Hi Dandy,
This is just a thought, but how about giving some thought to the idea of take Genesis and updating it (sources...providers)? My reasoning is with TV Addons shutting down urlresolver will over time prove useless. It would allow to have all the sources and providers in one addon instead of relying upon urlresolver getting updated. Specto uses urlresolver (his own version). Zen uses urlresolver. GenesisReborn uses urlresolver. A lot of addons use urlresolver. Like I said, it's just a thought. :).

I noticed you have urlresolver 3.0.33 on your site, which is an update over the latest one that I have (3.0.32). Did you update it yourself or is there a site where you picked it up? If the latter, which site?

Thanks for your time.

Later...

**Comment by dandy0850** [comment]
3.0.33 is latest as far as aware , updating Genesis sources wont resolve the links , other options will no doubt arise overtime. 
Its not all doom and gloom just yet plenty devs still putting in plenty of hours , things will settle

**Comment by bjgood** [comment]
Thanks for responding, Dandy.
I was talking about changing out the sources and resolvers that don't work with ones that do work. I'm presently using a older, modified version of Specto (before he included urlresolver as a dependency). With it I have about 5 sources and 10 resolvers that provide working links. I went into each source/resolver and checked/updated the base link. This got some of them working again.

I also use Zen, too.

Like I said, it's just a thought, dude. I would be a challenge.

Have a good one.

Later...

**Comment by dandy0850** [comment]
There is a repo somewhere with exodus updated
